### ISSUE TITLE
关于burpsuitV2021.10无法使用GetPlain Text获取明文

### ISSUE THREAD

**Issue by zeroboomboom** [whwlsfb/BurpCrypto#18]
如标题所述，点击GetPlain Text没有明文弹出，不清楚是不是burpsuit版本更新的问题，麻烦师傅看看

**Comment by whwlsfb** [comment]
我也是用的这个burp版本，请详细描述下使用步骤

**Comment by zeroboomboom** [comment]
具体是在intruder界面设置好爆破数据后，点击attack,进入到爆破界面，选择任意数据，点击扩展的Get PlainText，无法出现明文弹窗，另外，这边下载的Crypto插件是V0.1.9.1

**Comment by whwlsfb** [comment]
`任意数据`确定是通过BurpCrypto插件输出的数据吗

**Comment by zeroboomboom** [comment]
对，确定是用BurpCrypto插件输出的加密数据

**Comment by zeroboomboom** [comment]
师傅用的burpsuit上的BurpCrypto版本是多少呢，我试试你那个版本

**Comment by whwlsfb** [comment]
和你一样，也是2021.10，能提供下加密用的密钥信息吗

**Comment by zeroboomboom** [comment]
abcdefgabcdefg12，AES/ECB/PKCS5Padding,另外我刚刚想问师傅的是师傅的BurpCrypto插件版本是多少

**Comment by whwlsfb** [comment]
也是0.1.9.1

**Comment by whwlsfb** [comment]
> abcdefgabcdefg12，AES/ECB/PKCS5Padding,另外我刚刚想问师傅的是师傅的BurpCrypto插件版本是多少

我这边测试是正常的，你看下插件日志那里有没有错误信息

**Comment by zeroboomboom** [comment]
已经找到问题所在了，需要在请求包中选择具体的加密数据字符后点击Get PlainText才能显示明文密码，我之前都是直接在attack界面中选中请求包，辛苦师傅了

**Comment by whwlsfb** [comment]
ok，问题解决了就好
