### ISSUE TITLE
intruder模块出现未能加密的情况

### ISSUE THREAD

**Issue by baimasi** [whwlsfb/BurpCrypto#23]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/28396944/162379745-6b77d2cb-3816-4eb9-a435-59f6db484aaa.png">
爆破过程中发现有一些未能成功加密，这是哪里出了问题呢

**Comment by whwlsfb** [comment]
麻烦提供下所设置的参数和对应的payload
