### ISSUE TITLE
RSA 密钥过长导致error

### ISSUE THREAD

**Issue by liheng91** [whwlsfb/BurpCrypto#24]
在使用4096bit的RSA密钥时，无法添加process，会提示X509 error！我看了代码，其中定义的也是BigInteger类型，不知道为什么会出现这种错误？

**Comment by whwlsfb** [comment]
确认下使用的密钥是不是存在非base64的特殊字符，比如从流量中截取的key往往会被urlencode

**Comment by liheng91** [comment]
没有这种情况，这个密钥是在前端代码中定义的，不是在流量中传输的。

**Comment by whwlsfb** [comment]
密钥方便发一下吗？

**Comment by liheng91** [comment]
MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAOfyHVij4p3IpQE+tPuNPCkUk3xOqiP8/NYQD1Culr/UM7D394+JMCioHz7L2jCJWHn5QYD+SVcZYsLq+IPF0WJ7N0l1+2HL6Gw8Xpt47RMy6Y08XCbJS8YbdAQ+McFMJYLjcJK2Fow/4j5QK1cYGlGKx6LG3g08Ki5KVxXp+y5hAgMBAAECgYAwHzZhdpcEv2UkjfsEmbfamg9DYhrAnrNiQjC7P429POyAkeHF4OOh+8eHwsmA+m3l2IXzmk5jCLxJznBC/p7DF7zytzHg9Zmcgp+3moivMLCkV5QVvV/PLC5Mj8eR8mpOu8qPhp7IfsVnVVuFYM6QSR8XbV+9CMiZuVoa3uOkcQJBAPuqipxv4UQQNmX981JLfKnDIG0GFcZRx/fc7+MXEQSkTEvFF0bQOLzwVW/wdjT1JO/WUuT7EcT5K611bPI73DUCQQDr8KL7bG75ZwQlkAERvvIRopfO5Sad/ktB5NLozIVtg1aFuLZJXmeXF60Qmd59cG0/Ibn8hlLVxQ/BZD6hDhb9AkBmfr9zFPG2qa+t/C5T7uB3tzuGi3rkyTvay8V7RFKvBEb6eOuQ8I6bDHqPW2yZBtojP7OFBGfpQ92xCGj1gsGdAkEAzk66lRL57scvjxDefn/y94yvJdCl9d0YPWQzMDE2Ms53Z7JeYsVT24BuamfBbvpR7LQ3ByMFZ7tKzZY0VWwWmQJALoo4Qsr16xmAkcy7zx3o5ef00FixIaZE9cdreyskCpSM03fLSp8HCCBzB0IPxlLOX+VJtKbf4HKXl2h1XwOjLw==

**Comment by whwlsfb** [comment]
> MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAOfyHVij4p3IpQE+tPuNPCkUk3xOqiP8/NYQD1Culr/UM7D394+JMCioHz7L2jCJWHn5QYD+SVcZYsLq+IPF0WJ7N0l1+2HL6Gw8Xpt47RMy6Y08XCbJS8YbdAQ+McFMJYLjcJK2Fow/4j5QK1cYGlGKx6LG3g08Ki5KVxXp+y5hAgMBAAECgYAwHzZhdpcEv2UkjfsEmbfamg9DYhrAnrNiQjC7P429POyAkeHF4OOh+8eHwsmA+m3l2IXzmk5jCLxJznBC/p7DF7zytzHg9Zmcgp+3moivMLCkV5QVvV/PLC5Mj8eR8mpOu8qPhp7IfsVnVVuFYM6QSR8XbV+9CMiZuVoa3uOkcQJBAPuqipxv4UQQNmX981JLfKnDIG0GFcZRx/fc7+MXEQSkTEvFF0bQOLzwVW/wdjT1JO/WUuT7EcT5K611bPI73DUCQQDr8KL7bG75ZwQlkAERvvIRopfO5Sad/ktB5NLozIVtg1aFuLZJXmeXF60Qmd59cG0/Ibn8hlLVxQ/BZD6hDhb9AkBmfr9zFPG2qa+t/C5T7uB3tzuGi3rkyTvay8V7RFKvBEb6eOuQ8I6bDHqPW2yZBtojP7OFBGfpQ92xCGj1gsGdAkEAzk66lRL57scvjxDefn/y94yvJdCl9d0YPWQzMDE2Ms53Z7JeYsVT24BuamfBbvpR7LQ3ByMFZ7tKzZY0VWwWmQJALoo4Qsr16xmAkcy7zx3o5ef00FixIaZE9cdreyskCpSM03fLSp8HCCBzB0IPxlLOX+VJtKbf4HKXl2h1XwOjLw==

这个密钥是使用pkcs1编码的，目前插件只兼容pkcs8编码的密钥，需要进行转换

**Comment by liheng91** [comment]
好的，十分感谢解答！期待后期完善这一功能！！！
