### ISSUE TITLE
关于执行js代码中时间戳问题

### ISSUE THREAD

**Issue by qq87234770** [whwlsfb/BurpCrypto#25]
function getData() {
     return new Date().getTime();
}
正常执行返回时间戳：1651202830901
但在插件中使用Rhino返回的为：1.651202909136E12这种形式
不知是我使用问题还是啥。

**Comment by whwlsfb** [comment]
怪哦，我使用你的这段代码，输出的结果是正常的呢，能贴出你调用这个函数的部分的代码吗

**Comment by qq87234770** [comment]
我就是，将这个function放在execjs中生成个processor，之后再随便对一个字母A进行这个加密，加密
![image](https://user-images.githubusercontent.com/32386331/166212246-74da4659-c772-44d4-a8a5-2da704daafef.png)

![image](https://user-images.githubusercontent.com/32386331/166212270-ffa9ddc7-3ad2-4d04-b675-597dddb3a14e.png)

加密后：
![image](https://user-images.githubusercontent.com/32386331/166212310-716af777-a5e7-4c72-bbcf-3f8cafc2c1c7.png)

bp版本为2022.1.1，java版本17.0.2，使用javaw.exe进行运行

**Comment by whwlsfb** [comment]
问题解决了，可能是和java的类型转换有关系，临时解决方案是在后面加上`+ ""`，在js层转义成字符串类型。

```js
function getData() {
return new Date().getTime() + "";
}
```

**Comment by qq87234770** [comment]
感谢！
