### ISSUE TITLE
Exec Js 加载js库

### ISSUE THREAD

**Issue by W1one** [whwlsfb/BurpCrypto#27]
我在js中有这样一段：
var CryptoJS = require("crypto-js");
复制到Exec js中会报错：
org.mozilla.javascript.EcmaError: ReferenceError: "require" is not defined. (RhinoEngine#2)

该怎么解决呢？

**Comment by whwlsfb** [comment]
`require`是引入模块的功能，暂不支持哦，需要把模块源码都贴进去才能用。
