### ISSUE TITLE
rsa添加后无任何提示，测试aes正常

### ISSUE THREAD

**Issue by Ymigmli** [whwlsfb/BurpCrypto#32]
java 11
burp v2022.8.2
crypto v0.19.1 

![image](https://user-images.githubusercontent.com/47731874/192425664-61036210-7fab-49a1-a8a6-2c83f8682c4b.png)
![image](https://user-images.githubusercontent.com/47731874/192425721-5957d2ee-037a-4c08-ade9-8219893220d8.png)
010001
9E10BACC91A43532A9C3124C917DB596BF9F5BEDBB4B8D08E69695FC92188093DD9A3DCC30F88C60CA63673FAFC916F96B4EBC79D1280BDCDFBB236850AF0B2F5A252C42F098EEE3F3A79E37C394B87D47AE2FF55D9F838B6298D09231ECDA9952DBA7F76044F3C19F55F7F748CDE361064FC1E81B44F924B3ADE81638D5E8E9

**Comment by whwlsfb** [comment]
应该是个已知的bug #16 ，试下拉取master分支最新版本的代码，本地编译安装，是否能复现问题

**Comment by Ymigmli** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whwlsfb/BurpCrypto"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whwlsfb/BurpCrypto] rsa添加后无任何提示，测试aes正常 (Issue #32)





 
应该是个已知的bug #16 ，试下拉取master分支最新版本的代码，本地编译安装，是否能复现问题

**Comment by Ymigmli** [comment]
╰─ which burp                                                                                              ─╯
burp: aliased to setsid jdk-11.0.2/bin/java.exe -javaagent:BurpLoaderKeygen.jar --illegal-access=permit -Xmx8G -XX:-UseParallelGC -noverify -Dfile.encoding=utf-8 -jar burpsuite_pro_v2022.8.2.jar >/dev/null 2>&1 &

╰─ mvn -v                                                                                                  ─╯
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: \apache-maven
Java version: 11.0.2, vendor: Oracle Corporation, runtime: \jdk-11.0.2
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

╰─ mvn package                                                                                             ─╯
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for cn.wanghw:BurpCrypto:jar:0.1.9.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 47, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ line 12, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------< cn.wanghw:BurpCrypto >------------------------
[INFO] Building BurpCrypto 0.1.9.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ BurpCrypto ---
[WARNING] Using platform encoding (GBK actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory \BurpCrypto\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ BurpCrypto ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding GBK, i.e. build is platform dependent!
[INFO] Compiling 61 source files to \BurpCrypto\target\classes
[WARNING] /BurpCrypto/src/main/java/org/fife/ui/rtextarea/RTextAreaUI.java: \BurpCrypto\src\main\java\org\fife\ui\rtextarea\RTextAreaUI.java使用或覆盖了已过时的 API。
[WARNING] /BurpCrypto/src/main/java/org/fife/ui/rtextarea/RTextAreaUI.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[WARNING] /BurpCrypto/src/main/java/burp/aes/AesUIHandler.java: 某些输入文件使用了未经检查或不安全的操作。
[WARNING] /BurpCrypto/src/main/java/burp/aes/AesUIHandler.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ BurpCrypto ---
[WARNING] Using platform encoding (GBK actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory \BurpCrypto\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ BurpCrypto ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ BurpCrypto ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ BurpCrypto ---
[INFO] Building jar: \BurpCrypto\target\BurpCrypto-0.1.9.1.jar
[INFO]
[INFO] --- maven-shade-plugin:3.4.0:shade (default) @ BurpCrypto ---
[INFO] Including net.portswigger.burp.extender:burp-extender-api:jar:1.7.22 in the shaded jar.
[INFO] Including org.iq80.leveldb:leveldb:jar:0.12 in the shaded jar.
[INFO] Including org.iq80.leveldb:leveldb-api:jar:0.12 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:21.0 in the shaded jar.
[INFO] Including org.mozilla:rhino:jar:1.7.13 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.10 in the shaded jar.
[INFO] Including com.fifesoft:languagesupport:jar:3.1.2 in the shaded jar.
[INFO] Including com.fifesoft:autocomplete:jar:3.1.1 in the shaded jar.
[INFO] Including com.fifesoft:rsyntaxtextarea:jar:3.1.3 in the shaded jar.
[INFO] Including net.sourceforge.htmlunit:htmlunit:jar:2.48.0 in the shaded jar.
[INFO] Including xalan:xalan:jar:2.7.2 in the shaded jar.
[INFO] Including xalan:serializer:jar:2.7.2 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.12.0 in the shaded jar.
[INFO] Including org.apache.commons:commons-text:jar:1.9 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpmime:jar:4.5.13 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpclient:jar:4.5.13 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpcore:jar:4.4.13 in the shaded jar.
[INFO] Including net.sourceforge.htmlunit:htmlunit-core-js:jar:2.48.0 in the shaded jar.
[INFO] Including net.sourceforge.htmlunit:neko-htmlunit:jar:2.48.0 in the shaded jar.
[INFO] Including xerces:xercesImpl:jar:2.12.0 in the shaded jar.
[INFO] Including xml-apis:xml-apis:jar:1.4.01 in the shaded jar.
[INFO] Including net.sourceforge.htmlunit:htmlunit-cssparser:jar:1.7.0 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.8.0 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.2 in the shaded jar.
[INFO] Including commons-net:commons-net:jar:3.8.0 in the shaded jar.
[INFO] Including org.brotli:dec:jar:0.1.2 in the shaded jar.
[INFO] Including com.shapesecurity:salvation2:jar:3.0.0 in the shaded jar.
[INFO] Including org.eclipse.jetty.websocket:websocket-client:jar:9.4.38.v20210224 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-client:jar:9.4.38.v20210224 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-http:jar:9.4.38.v20210224 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-util:jar:9.4.38.v20210224 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-io:jar:9.4.38.v20210224 in the shaded jar.
[INFO] Including org.eclipse.jetty.websocket:websocket-common:jar:9.4.38.v20210224 in the shaded jar.
[INFO] Including org.eclipse.jetty.websocket:websocket-api:jar:9.4.38.v20210224 in the shaded jar.
[INFO] Including org.yaml:snakeyaml:jar:1.29 in the shaded jar.
[INFO] Including commons-httpclient:commons-httpclient:jar:3.1 in the shaded jar.
[INFO] Including cn.hutool:hutool-crypto:jar:5.7.16 in the shaded jar.
[INFO] Including cn.hutool:hutool-core:jar:5.7.16 in the shaded jar.
[INFO] Including com.squareup.okhttp3:okhttp:jar:4.9.3 in the shaded jar.
[INFO] Including com.squareup.okio:okio:jar:2.8.0 in the shaded jar.
[INFO] Including org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.4.0 in the shaded jar.
[INFO] Including org.jetbrains.kotlin:kotlin-stdlib:jar:1.4.10 in the shaded jar.
[INFO] Including org.jetbrains:annotations:jar:13.0 in the shaded jar.
[INFO] Dependency-reduced POM written at: \BurpCrypto\dependency-reduced-pom.xml
[WARNING] jetty-client-9.4.38.v20210224.jar, jetty-http-9.4.38.v20210224.jar, jetty-io-9.4.38.v20210224.jar, jetty-util-9.4.38.v20210224.jar, websocket-api-9.4.38.v20210224.jar, websocket-client-9.4.38.v20210224.jar, websocket-common-9.4.38.v20210224.jar define 1 overlapping resource:
[WARNING]   - about.html
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See https://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Attaching shaded artifact.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.017 s
[INFO] Finished at: 2022-10-25T15:28:12+08:00
[INFO] ------------------------------------------------------------------------

rsa/sm4/zuc还是没有反应

**Comment by whwlsfb** [comment]
> java 11 burp v2022.8.2 crypto v0.19.1
> 
> ![image](https://user-images.githubusercontent.com/47731874/192425664-61036210-7fab-49a1-a8a6-2c83f8682c4b.png) ![image](https://user-images.githubusercontent.com/47731874/192425721-5957d2ee-037a-4c08-ade9-8219893220d8.png) 010001 9E10BACC91A43532A9C3124C917DB596BF9F5BEDBB4B8D08E69695FC92188093DD9A3DCC30F88C60CA63673FAFC916F96B4EBC79D1280BDCDFBB236850AF0B2F5A252C42F098EEE3F3A79E37C394B87D47AE2FF55D9F838B6298D09231ECDA9952DBA7F76044F3C19F55F7F748CDE361064FC1E81B44F924B3ADE81638D5E8E9

参数填反了，把参数调转就好了

**Comment by Ymigmli** [comment]
傻瓜问题，感谢您的回复。
