### ISSUE TITLE
des 加密填充没有Pkcs7

### ISSUE THREAD

**Issue by MrWQ** [whwlsfb/BurpCrypto#4]
des 加密填充没有Pkcs7，对于使用pkcs7的网站加密不方便使用

**Comment by whwlsfb** [comment]
请问尝试过使用Pkcs5填充模式吗，大部分情况下这两种填充模式是可以互换的。

> https://crypto.stackexchange.com/questions/9043/what-is-the-difference-between-pkcs5-padding-and-pkcs7-padding

**Comment by MrWQ** [comment]
好的，谢谢，知识又增加了
